; PlatformIO Project Configuration File
; ESP32S3 (ESP1) - Broker MQTT + lógica de controle

[env:esp32s3_broker]
platform = espressif32
board    = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
