; PlatformIO Project Configuration File
; ESP32S3 - Broker MQTT + Lógica de Controle

[env:esp32s3_broker]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    martin-ger/uMQTTBroker @ ^1.1.0
monitor_speed = 115200
