; PlatformIO Project Configuration File
; ESP8266 (ESP2) - Sensor: lê ADC e publica em MQTT

[env:esp8266_sensor]
platform = espressif8266
board    = esp01_1m
framework = esp8266-rtos-sdk
monitor_speed = 115200
